import { ArrowRight, BookOpenCheck, Calculator, Code2, Compass, FlaskConical, HeartHandshake, Languages, Lightbulb, MonitorSmartphone, Palette, Route, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";
import Reveal from "../components/Reveal";
import StaffCard from "../components/StaffCard";
import { CTASection, PageHero, SectionHeading, VisualCard } from "../components/UI";
import { blogCategories, courses } from "../data/catalog";
import { images } from "../data/site";
import { teamMembers } from "../data/team";

const values = [[Compass, "Clarity", "Make important academic information easier to understand."], [Route, "Progress", "Connect today’s course choice with the next meaningful milestone."], [UsersRound, "Respect", "Create a thoughtful, student-centred experience."], [Lightbulb, "Curiosity", "Encourage learning beyond minimum requirements."], [BookOpenCheck, "Responsibility", "Support informed choices and honest learning habits."], [MonitorSmartphone, "Opportunity", "Make pathways and support easier to discover digitally."]];
const elementarySubjects = [[Calculator, "Mathematics"], [Languages, "English & French"], [FlaskConical, "Science"], [Code2, "Technology"], [Palette, "Creative Arts"], [HeartHandshake, "Health & Active Living"]];

export default function AboutPage() {
  return (
    <>
      <PageHero eyebrow="ABOUT NEXUS" title="A Modern School Built Around Student Progress." text="Nexus brings supportive elementary learning, clear Ontario secondary course discovery, thoughtful pathway planning and a modern digital experience together." image={images.campus} imageAlt="Students walking together on a modern education campus" breadcrumbs={[{ label: "About Us" }]}>
        <Link className="btn btn-primary" to="/courses">Explore Courses <ArrowRight size={17} /></Link><Link className="btn btn-secondary" to="/inquiry">Start an Inquiry</Link>
      </PageHero>
      <Reveal as="section" className="section container about-story">
        <div><span className="eyebrow">OUR APPROACH</span><h2>Clarity before complexity.</h2><p className="large-copy">Students should be able to understand what they are taking, why it matters and what comes next. Nexus organizes course information and support around those practical questions.</p><p>That means thoughtful course discovery, honest pathway context, a clear handoff into digital learning and visible support whenever a decision is uncertain.</p></div>
        <div className="about-stat-panel"><div><strong>{courses.length}+</strong><span>course records in the current catalogue</span></div><div><strong>9–12</strong><span>Ontario secondary grade levels</span></div><div><strong>{blogCategories.length}</strong><span>student and family guide categories</span></div></div>
      </Reveal>
      <Reveal as="section" className="section container mission-grid">
        <div className="mission-photo"><img src={images.familySupport} alt="Teacher supporting learners during a classroom conversation" width="1400" height="950" loading="lazy" decoding="async" /></div>
        <div><span className="eyebrow">WHO WE ARE</span><h2>Learning should feel clear, supported and connected to a purpose.</h2><p>Nexus is building a student-centred experience across learning stages. Families can explore information, understand next steps and reach the appropriate support without navigating an impersonal system.</p><div className="mission-cards"><article><strong>Our mission</strong><p>Make quality learning and pathway information more accessible, understandable and responsive to individual goals.</p></article><article><strong>Our approach</strong><p>Combine human guidance with a maintainable digital experience that keeps learning routes visible.</p></article></div></div>
      </Reveal>
      <Reveal as="section" className="section soft-section"><div className="container"><SectionHeading eyebrow="OUR VALUES" title="Principles That Keep Progress Human." text="A premium digital experience matters most when it makes the academic journey clearer and more respectful." /><div className="feature-grid">{values.map(([Icon, title, text]) => <article className="feature-card" key={title}><span className="icon-bubble"><Icon size={21} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></Reveal>
      <Reveal as="section" className="section container"><SectionHeading eyebrow="WHAT MAKES NEXUS DIFFERENT" title="Designed Around Real Student Questions." /><div className="visual-grid three"><VisualCard image={images.planning} alt="Student and mentor reviewing a plan together" eyebrow="ACADEMIC PATHWAYS" title="What should I take next?" text="Course codes, grade levels and pathway context make next steps easier to compare." /><VisualCard image={images.classroom} alt="Students learning in a bright modern classroom" eyebrow="TECHNOLOGY" title="Where does learning happen?" text="The public website connects registered students clearly to a modern LMS experience." /><VisualCard image={images.graduation} alt="Graduates celebrating an academic milestone" eyebrow="MEANINGFUL SUPPORT" title="How does this fit my goal?" text="Planning tools and inquiry paths help connect current choices to future possibilities." /></div></Reveal>
      <Reveal as="section" className="section elementary-band"><div className="container elementary-grid"><div><span className="eyebrow">ELEMENTARY LEARNING</span><h2>Bright beginnings, built with care.</h2><p>Age-appropriate learning can be warm and engaging without losing academic structure. Nexus can support younger learners across foundational subjects while keeping family communication clear.</p><div className="elementary-subjects">{elementarySubjects.map(([Icon, label]) => <span key={label}><Icon size={19} />{label}</span>)}</div></div><div className="elementary-photo"><img src={images.elementary} alt="Young students working together in a bright classroom" width="1400" height="1000" loading="lazy" decoding="async" /><span aria-hidden="true"><BookOpenCheck size={26} /></span><i aria-hidden="true">A B C</i></div></div></Reveal>
      <Reveal as="section" className="section container secondary-split"><div className="secondary-photo"><img src={images.secondaryStudents} alt="Secondary students learning together" width="1400" height="950" loading="lazy" decoding="async" /></div><div><SectionHeading eyebrow="SECONDARY LEARNING" title="Course choices connected to what comes next." text="Students can search the full Ontario secondary catalogue, compare prerequisites and connect Grade 9–12 decisions with graduation, college, university and career research." /><Link className="btn btn-primary" to="/courses">Explore Secondary Courses <ArrowRight size={17} /></Link></div></Reveal>
      <Reveal as="section" className="section container split-feature"><div className="split-feature-image"><img src={images.mentoring} alt="Teacher mentoring students in a classroom" width="1400" height="900" loading="lazy" decoding="async" /></div><div><SectionHeading eyebrow="THE NEXUS EXPERIENCE" title="Modern Does Not Have to Mean Impersonal." text="Nexus uses technology to reduce friction while keeping support visible. Students and families can browse, compare, plan and ask before a decision becomes urgent." /><ul className="plain-list"><li>Searchable course catalogue</li><li>Grade-based exploration</li><li>Pathway and prerequisite context</li><li>Clear student-support routes</li><li>Direct LMS access for enrolled students</li></ul><Link className="text-link" to="/student-support">Explore Student Support <ArrowRight size={16} /></Link></div></Reveal>
      <Reveal as="section" className="section soft-section"><div className="container about-team-preview"><div><SectionHeading eyebrow="EXPERIENCED PEOPLE & DIGITAL SUPPORT" title="Meet the people behind the experience." text="The public directory grows only with school-approved names, roles, biographies, qualifications and photos." /><Link className="btn btn-secondary" to="/about/team">Meet the Nexus Team <ArrowRight size={17} /></Link></div><StaffCard member={teamMembers[0]} compact /></div></Reveal>
      <Reveal as="section" className="section container technology-credit"><div><span className="eyebrow">DIGITAL LEARNING & TECHNOLOGY</span><h2>A reliable bridge from the public website to the learning portal.</h2><p>Nexus Education's digital experience, including the school website and learning management portal implementation, is developed and supported by MSPixelPulse Web Solutions.</p><div className="button-row"><a className="btn btn-primary" href="https://mspixelpulse.com" target="_blank" rel="noreferrer">Visit MSPixelPulse</a></div></div><div className="technology-mark"><MonitorSmartphone size={48} /><strong>Accessible. Responsive. Maintainable.</strong><span>Technology should support learning—not get in its way.</span></div></Reveal>
      <CTASection title="See Where Nexus Can Take You." text="Start with the course, prerequisite or future goal you want to understand better." />
    </>
  );
}
