import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './styles/globals.css'
import './styles/components.css'
import './styles/responsive.css'
import './styles/brand-theme.css'
import './styles/footer-logo-fix.css'
import './styles/course-detail-color-fix.css'
import './styles/footer-mobile-lms-fix.css'
import './styles/future-education-section-fix.css'
import './styles/brand-guidelines.css'
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>)
